try {
    throw 2;
}
catch (a) {
    console.log(a);
}
//console.log(a);